services:
  eln-notebook:
    #build: .
    # This naming convention allows for easy pushing/pulling
    image: schatzm/eln-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    command: >
      jupyter lab 
      --ip=0.0.0.0 
      --port=8888 
      --no-browser 
      --allow-root 
      --ServerApp.token=''      
      --ServerApp.password=''